server {
    listen 80;

    resolver 127.0.0.11 valid=5s ipv6=off;

    location / {
        set $app_upstream app;
        proxy_pass http://$app_upstream:5000;
        proxy_next_upstream error timeout http_502 http_503 http_504;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
