upstream album_app {
    server app:5000;
}

server {
    listen 80;

    location / {
        proxy_pass http://album_app;
        proxy_next_upstream error timeout http_502 http_503 http_504;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
